# Generated by Django 4.1.7 on 2023-03-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_author_books_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
